### ISSUE TITLE
Turn into an Arduino library

### ISSUE THREAD

**Issue by probonopd** [mbs38/siedle-in-home-bus-avr#1]
Turning this into an Arduino library could lead to exponentially more users, as it would make the code more MCU independent. A target that may be especially worthwhile is the [Arduino Core for Nordic Semiconductor nRF5 based boards](https://github.com/sandeepmistry/arduino-nRF5) that use Bluetooth Low Energy (e.g., search ebay.com for NRF51822-04).

By the way, there is an Arduino core for the ATtiny2313, too.

**Comment by mbs38** [comment]
Using Ardiuno feels cumbersome to me. So usually I'll just go bare metal. Right now I don't have the time to work on this but I'll probably make an Arduino lib out of this.
Btw on the security of the in-home-bus: there is none. Replay attacks work just fine.

**Comment by probonopd** [comment]
>  I'll probably make an Arduino lib out of this.

Cool. I guarantee it will bring many more users to the project.

> Btw on the security of the in-home-bus: there is none. Replay attacks work just fine.

Interesting. I feel a 35C3 talk coming; security by obscurity never works.

**Comment by mbs38** [comment]
https://github.com/mbs38/siedle-in-home-bus-arduino
A hardware adaptor has already been designed. Some resistors still need to have their values calculated though.

**Comment by probonopd** [comment]
Thank you. Great work!

**Comment by probonopd** [comment]
The ino sketch appears to be missing from https://github.com/mbs38/siedle-in-home-bus-arduino, maybe it was not uploaded?

**Comment by mbs38** [comment]
Hi,
it is not finished yet. I would like to make the hardware first, because I don't want to publish untested software. Unfortunately I don't have enough spare time atm... Stay tuned :-)

**Comment by mbs38** [comment]
Update:
I've decided that I won't do this as I don't have any use for an arduino based solution myself.

**Comment by lukasloetkolben** [comment]
> Update: I've decided that I won't do this as I don't have any use for an arduino based solution myself.

i saw you deleted the Repo. Would it be possible for you to share your arduino library again?

**Comment by mbs38** [comment]
> > Update: I've decided that I won't do this as I don't have any use for an arduino based solution myself.
> 
> i saw you deleted the Repo. Would it be possible for you to share your arduino library again?

Hi Lukas,
I only started doing the hardware part and never even began implementing a library for Arduino so there really is nothing I can share.

Max
